---
first_name:
  validators:
    length:
      label: "&FIRST_NAME"
      min: 1
      max: 20
      message: VALIDATE.LENGTH_RANGE
    required:
      label: "&FIRST_NAME"
      message: VALIDATE.REQUIRED
last_name:
  validators:
    length:
      label: "&LAST_NAME"
      min: 1
      max: 30
      message: VALIDATE.LENGTH_RANGE
address:
  validators:
    regex:
      regex: \d{1,6}\s(?:[A-Za-z0-9#]+\s){0,7}(?:[A-Za-z0-9#]+,)\s*(?:[A-Za-z]+\s){0,3}(?:[A-Za-z]+,)\s*[A-Z]{2}\s*\d{5}
      message: You did not provide a valid address.
phone:
  validators:
    regex:
      regex: ^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$
      message: You did not provide a valid phone number.
locale:
  validators:
    required:
      label: "&LOCALE"
      domain: server
      message: VALIDATE.REQUIRED
